# Generated by Django 5.0.6 on 2025-09-29 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TEMPLATES', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la rama')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está activa')),
                ('is_main', models.BooleanField(default=False, verbose_name='Es la rama principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('base_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VERSIONS.branch', verbose_name='Rama base')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='TEMPLATES.template', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Rama',
                'verbose_name_plural': 'Ramas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(verbose_name='Número de versión')),
                ('branch_name', models.CharField(default='main', max_length=100, verbose_name='Nombre de la rama')),
                ('commit_hash', models.CharField(max_length=40, unique=True, verbose_name='Hash del commit')),
                ('html_content', models.TextField(verbose_name='Contenido HTML')),
                ('css_content', models.TextField(verbose_name='Contenido CSS')),
                ('js_content', models.TextField(blank=True, verbose_name='Contenido JavaScript')),
                ('commit_message', models.TextField(verbose_name='Mensaje del commit')),
                ('changes_summary', models.JSONField(default=dict, verbose_name='Resumen de cambios')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('committed', 'Confirmado'), ('merged', 'Fusionado'), ('rollback', 'Rollback')], default='draft', max_length=20, verbose_name='Estado')),
                ('is_current', models.BooleanField(default=False, verbose_name='Es la versión actual')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_versions', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='VERSIONS.templateversion', verbose_name='Versión padre')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='TEMPLATES.template', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Versión de Plantilla',
                'verbose_name_plural': 'Versiones de Plantillas',
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number', 'branch_name')},
            },
        ),
        migrations.CreateModel(
            name='MergeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('approved', 'Aprobada'), ('merged', 'Fusionada'), ('closed', 'Cerrada'), ('rejected', 'Rechazada')], default='open', max_length=20, verbose_name='Estado')),
                ('conflicts', models.JSONField(default=list, verbose_name='Conflictos detectados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fusión')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_merge_requests', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_merge_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_merges', to='VERSIONS.branch', verbose_name='Rama origen')),
                ('target_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_merges', to='VERSIONS.branch', verbose_name='Rama destino')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_requests', to='TEMPLATES.template', verbose_name='Plantilla')),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_merges', to='VERSIONS.templateversion', verbose_name='Versión origen')),
                ('target_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_merges', to='VERSIONS.templateversion', verbose_name='Versión destino')),
            ],
            options={
                'verbose_name': 'Solicitud de Fusión',
                'verbose_name_plural': 'Solicitudes de Fusión',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar'), ('rollback', 'Rollback'), ('merge', 'Fusionar'), ('branch', 'Crear rama')], max_length=20, verbose_name='Acción')),
                ('description', models.TextField(verbose_name='Descripción del cambio')),
                ('changes_detail', models.JSONField(default=dict, verbose_name='Detalle de cambios')),
                ('affected_files', models.JSONField(default=list, verbose_name='Archivos afectados')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='TEMPLATES.template', verbose_name='Plantilla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VERSIONS.templateversion', verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Registro de Cambios',
                'verbose_name_plural': 'Registros de Cambios',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='base_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VERSIONS.templateversion', verbose_name='Versión base'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('template', 'name')},
        ),
    ]
