# Generated by Django 5.0.6 on 2025-09-29 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PARSER', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color (hex)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Categoría de Plantilla',
                'verbose_name_plural': 'Categorías de Plantillas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la plantilla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('html_file_path', models.CharField(max_length=500, verbose_name='Ruta del archivo HTML')),
                ('css_file_path', models.CharField(max_length=500, verbose_name='Ruta del archivo CSS')),
                ('js_file_path', models.CharField(max_length=500, verbose_name='Ruta del archivo JS')),
                ('html_content', models.TextField(verbose_name='Contenido HTML')),
                ('css_content', models.TextField(verbose_name='Contenido CSS')),
                ('js_content', models.TextField(blank=True, verbose_name='Contenido JavaScript')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('archived', 'Archivada')], default='draft', max_length=20, verbose_name='Estado')),
                ('tags', models.JSONField(default=list, verbose_name='Etiquetas')),
                ('placeholders', models.JSONField(default=list, verbose_name='Lista de placeholders')),
                ('placeholder_descriptions', models.JSONField(default=dict, verbose_name='Descripciones de placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_templates', to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PARSER.document', verbose_name='Documento origen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TEMPLATES.templatecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plantilla',
                'verbose_name_plural': 'Plantillas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplatePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la vista previa')),
                ('test_data', models.JSONField(default=dict, verbose_name='Datos de prueba')),
                ('rendered_html', models.TextField(verbose_name='HTML renderizado')),
                ('viewport_width', models.PositiveIntegerField(default=1200, verbose_name='Ancho de viewport')),
                ('viewport_height', models.PositiveIntegerField(default=800, verbose_name='Alto de viewport')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='TEMPLATES.template', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Vista Previa de Plantilla',
                'verbose_name_plural': 'Vistas Previas de Plantillas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceholderDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del placeholder')),
                ('display_name', models.CharField(max_length=150, verbose_name='Nombre para mostrar')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('placeholder_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('date', 'Fecha'), ('email', 'Email'), ('url', 'URL'), ('image', 'Imagen'), ('boolean', 'Booleano'), ('list', 'Lista')], default='text', max_length=20, verbose_name='Tipo de placeholder')),
                ('is_required', models.BooleanField(default=False, verbose_name='Es requerido')),
                ('default_value', models.TextField(blank=True, verbose_name='Valor por defecto')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longitud máxima')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longitud mínima')),
                ('validation_regex', models.CharField(blank=True, max_length=500, verbose_name='Expresión regular de validación')),
                ('position_info', models.JSONField(default=dict, verbose_name='Información de posición')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_definitions', to='TEMPLATES.template', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Definición de Placeholder',
                'verbose_name_plural': 'Definiciones de Placeholders',
                'ordering': ['name'],
                'unique_together': {('template', 'name')},
            },
        ),
    ]
