# Generated by Django 5.0.6 on 2025-09-29 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original del archivo')),
                ('document_type', models.CharField(choices=[('docx', 'Word Document (.docx)'), ('xls', 'Excel Spreadsheet (.xls)'), ('xlsx', 'Excel Spreadsheet (.xlsx)'), ('pdf', 'PDF Document (.pdf)')], max_length=10, verbose_name='Tipo de documento')),
                ('file_path', models.FileField(upload_to='documents/', verbose_name='Archivo')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamaño del archivo (bytes)')),
                ('status', models.CharField(choices=[('uploaded', 'Subido'), ('processing', 'Procesando'), ('completed', 'Completado'), ('error', 'Error')], default='uploaded', max_length=20, verbose_name='Estado')),
                ('processing_log', models.TextField(blank=True, null=True, verbose_name='Log de procesamiento')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ParsedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(verbose_name='Texto extraído')),
                ('structured_data', models.JSONField(default=dict, verbose_name='Datos estructurados')),
                ('style_info', models.JSONField(default=dict, verbose_name='Información de estilo')),
                ('fonts_used', models.JSONField(default=list, verbose_name='Fuentes utilizadas')),
                ('colors_used', models.JSONField(default=list, verbose_name='Colores utilizados')),
                ('placeholders_detected', models.JSONField(default=list, verbose_name='Placeholders detectados')),
                ('red_text_content', models.JSONField(default=list, verbose_name='Contenido en texto rojo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_content', to='PARSER.document')),
            ],
            options={
                'verbose_name': 'Contenido Parseado',
                'verbose_name_plural': 'Contenidos Parseados',
            },
        ),
    ]
